/*Exemplo de Programa na linguagem L
* Comentario 
* Mais de
* Uma linha
* - Teste HEXA
*/

char _Identificador;

main {
  /* Programa Principal */
  _Identificador := 04Ah; /*Caracter J tabela ASCII*/
  write(_Identificador);
  _Identificador := 010; /*Caracter new Line tabela ASCII*/
  write(_Identificador);
  _Identificador := '$'; /*Caracter $ tabela ASCII*/
  write(_Identificador);
  _Identificador := 04Gh; /*Hexa Inválido*/
  write(_Identificador);
}